# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x07\x65xample\"\xd2\x01\n\rTelemetryTask\x12\x0e\n\x06taskID\x18\x01 \x01(\x07\x12\r\n\x05\x61ppID\x18\x02 \x01(\x07\x12\x0e\n\x06kindID\x18\x03 \x01(\x07\x12\x0b\n\x03sIP\x18\x04 \x01(\t\x12\x0b\n\x03\x64Ip\x18\x05 \x01(\t\x12\r\n\x05sPORT\x18\x06 \x01(\t\x12\r\n\x05\x64PORT\x18\x07 \x01(\t\x12\x10\n\x08protocol\x18\x08 \x01(\t\x12\x0b\n\x03mop\x18\t \x01(\x07\x12\x0c\n\x04\x66req\x18\n \x01(\x07\x12\x10\n\x08metadata\x18\x0b \x01(\t\x12\r\n\x05\x61live\x18\x0c \x01(\t\x12\x0c\n\x04Name\x18\r \x01(\t\"\x1a\n\x07Success\x12\x0f\n\x07success\x18\x01 \x01(\t2D\n\nFormatData\x12\x36\n\x08\x44oFormat\x12\x16.example.TelemetryTask\x1a\x10.example.Success\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TELEMETRYTASK._serialized_start=24
  _TELEMETRYTASK._serialized_end=234
  _SUCCESS._serialized_start=236
  _SUCCESS._serialized_end=262
  _FORMATDATA._serialized_start=264
  _FORMATDATA._serialized_end=332
# @@protoc_insertion_point(module_scope)

